### PR TITLE
Stop massive spams from one line 

### PR DESCRIPTION
**Pull request by NIXC**
msg:
covfefe is dead, Astraeus. You should of known, you are the AI for FTL station.
rsp:
You best not be talking about me, you little punk.
Reeee covfefe is dead
Reeee its a ship not a station get it right
It's could HAVE or would HAVE, never could of or would of

The spam was funny the first time but the meme is dead.
Now it just responds with the first thing it finds, except for status calls and admin calls which are unaffected.
Please test this first I dont know how to javascript.

### CODE REVIEW

**Comment by the-og-gear** [comment]
Meh. The spam is fun.
I say we leave it. It doesn't happen often.

**Comment by NIXC** [comment]
All it takes is one shitter to make a discord account and fill all the non-admin channels with cancer

**Comment by NIXC** [comment]
@monster860 I think your the only one who can merge this, What do you think about it?

**Comment by the-og-gear** [comment]
I don't know if the maintainers can merge, though it is part of the FTL group, makes me think they would be able to.

**Comment by alexkar598** [comment]
@NIXC a recent commit fixed this issue,you should close this pr

**Comment by NIXC** [comment]
Aight. Its not like it was going to get looked at anyway :P

**Pull request closed without merging**
